[2025-10-23T20:44:26.936+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T20:44:26.971+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v1.get_name manual__2025-10-23T20:44:23.995612+00:00 [queued]>
[2025-10-23T20:44:26.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v1.get_name manual__2025-10-23T20:44:23.995612+00:00 [queued]>
[2025-10-23T20:44:26.985+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T20:44:27.010+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2025-10-23 20:44:23.995612+00:00
[2025-10-23T20:44:27.043+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T20:44:27.047+0000] {standard_task_runner.py:72} INFO - Started process 2204 to run task
[2025-10-23T20:44:27.059+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v1', 'get_name', 'manual__2025-10-23T20:44:23.995612+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmp_68bazu0']
[2025-10-23T20:44:27.061+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask get_name
[2025-10-23T20:44:27.232+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v1.get_name manual__2025-10-23T20:44:23.995612+00:00 [running]> on host c65f76f8d89c
[2025-10-23T20:44:27.420+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v1' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T20:44:23.995612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T20:44:23.995612+00:00'
[2025-10-23T20:44:27.423+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T20:44:27.428+0000] {python.py:240} INFO - Done. Returned value was: Jerry
[2025-10-23T20:44:27.473+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T20:44:27.475+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v1, task_id=get_name, run_id=manual__2025-10-23T20:44:23.995612+00:00, execution_date=20251023T204423, start_date=20251023T204426, end_date=20251023T204427
[2025-10-23T20:44:27.557+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T20:44:27.576+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
