[2025-10-23T18:44:31.661+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T18:44:31.678+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:44:29.931765+00:00 [queued]>
[2025-10-23T18:44:31.691+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:44:29.931765+00:00 [queued]>
[2025-10-23T18:44:31.692+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T18:44:31.707+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2025-10-23 18:44:29.931765+00:00
[2025-10-23T18:44:31.714+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=598) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T18:44:31.716+0000] {standard_task_runner.py:72} INFO - Started process 599 to run task
[2025-10-23T18:44:31.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'first_task', 'manual__2025-10-23T18:44:29.931765+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpn6mgnok5']
[2025-10-23T18:44:31.720+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask first_task
[2025-10-23T18:44:31.792+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.first_task manual__2025-10-23T18:44:29.931765+00:00 [running]> on host c65f76f8d89c
[2025-10-23T18:44:31.890+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:44:29.931765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:44:29.931765+00:00'
[2025-10-23T18:44:31.891+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T18:44:31.914+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-23T18:44:31.917+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task!']
[2025-10-23T18:44:31.929+0000] {subprocess.py:99} INFO - Output:
[2025-10-23T18:44:31.931+0000] {subprocess.py:106} INFO - hello world, this is the first task!
[2025-10-23T18:44:31.932+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-10-23T18:44:31.972+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T18:44:31.973+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=first_task, run_id=manual__2025-10-23T18:44:29.931765+00:00, execution_date=20251023T184429, start_date=20251023T184431, end_date=20251023T184431
[2025-10-23T18:44:32.015+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T18:44:32.039+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-23T18:44:32.042+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
