[2025-10-23T20:19:57.446+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T20:19:57.466+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.get_name manual__2025-10-23T20:19:55.985570+00:00 [queued]>
[2025-10-23T20:19:57.480+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.get_name manual__2025-10-23T20:19:55.985570+00:00 [queued]>
[2025-10-23T20:19:57.482+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T20:19:57.500+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_name> on 2025-10-23 20:19:55.985570+00:00
[2025-10-23T20:19:57.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1876) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T20:19:57.513+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v05', 'get_name', 'manual__2025-10-23T20:19:55.985570+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp_row6tb9']
[2025-10-23T20:19:57.514+0000] {standard_task_runner.py:72} INFO - Started process 1877 to run task
[2025-10-23T20:19:57.514+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask get_name
[2025-10-23T20:19:57.605+0000] {task_command.py:467} INFO - Running <TaskInstance: our_dag_with_python_operator_v05.get_name manual__2025-10-23T20:19:55.985570+00:00 [running]> on host c65f76f8d89c
[2025-10-23T20:19:57.730+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v05' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T20:19:55.985570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T20:19:55.985570+00:00'
[2025-10-23T20:19:57.733+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T20:19:57.793+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-23T20:19:57.812+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T20:19:57.813+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v05, task_id=get_name, run_id=manual__2025-10-23T20:19:55.985570+00:00, execution_date=20251023T201955, start_date=20251023T201957, end_date=20251023T201957
[2025-10-23T20:19:57.851+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T20:19:57.875+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-23T20:19:57.877+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
